class Animations
{
public async void animation()
{
Console.WriteLine("             |>  ");
Console.WriteLine("        |    |    |");
Console.WriteLine("       )_)  )_)  )_)                                       |>");
Console.WriteLine("      )___))___))___)\\                               |    |    |");
Console.WriteLine("     )____)____)_____)\\                             (_(  (_(  (_(");
Console.WriteLine("    ____|____|____|____\\_____                     /(___((___((___( ");
Console.WriteLine("----\\              //                            /(____(____(_____(");
Console.WriteLine("^^^^^^^^^^^^^^^^^^^^  ^^^^ ^^^^^^^^^^       _____//___|____|____|_____ ");
Console.WriteLine("^^^^^^^ ^        ^^^^^^^^                          \\                //^^ ^^^^^ ^^^^^^^^");
Console.WriteLine("^^^^^^^^^^^^               ^^^^ ^^^^    ^^      ^^^      ^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^ ");
Console.WriteLine("^^^^^^^^            ^^^^^^^^^^^^                          ^^^^^^^^^^^^^            ^^^^^^^^^^^^^ ");
await Task.Delay(500);
Console.Clear();
Console.WriteLine("             |>  ");
Console.WriteLine("        |    |    |");
Console.WriteLine("       )_)  )_)  )_)                                    |>");
Console.WriteLine("      )___))___))___)\\                            |    |    |");
Console.WriteLine("     )____)____)_____)\\                          (_(  (_(  (_(");
Console.WriteLine("    ____|____|____|____\\_____                  /(___((___((___( ");
Console.WriteLine("----\\              //                         /(____(____(_____(");
Console.WriteLine("^^^^^^   ^^^^^^^^^^^  ^^^^ ^^^  ^^^^^    _____//___|____|____|_____ ");
Console.WriteLine("^^^^^^^ ^        ^^^^^^^^                       \\                //^^ ^^^^^ ^   ^^^^^");
Console.WriteLine("^^^^^^^  ^^^^^           ^^^  ^ ^^^^    ^^      ^^^      ^^^  ^^^^^^^^^^^^^   ^^^^^^^^^^^^ ^^^^^ ");
Console.WriteLine("^^^^^^^^            ^^^^^^^^^^^^                          ^^^^^^^^^            ^^^^^^^   ^^^^^^ ");
await Task.Delay(500);
Console.Clear();
Console.WriteLine("             |>  ");
Console.WriteLine("        |    |    |");
Console.WriteLine("       )_)  )_)  )_)                                  |>");
Console.WriteLine("      )___))___))___)\\                          |    |    |");
Console.WriteLine("     )____)____)_____)\\                        (_(  (_(  (_(");
Console.WriteLine("    ____|____|____|____\\____                 /(___((___((___( ");
Console.WriteLine("----\\              //                       /(____(____(_____(");
Console.WriteLine("^^^^^^        ^^^^^^  ^^^^ ^^   ^^     _____//___|____|____|_____ ");
Console.WriteLine("^^^^^^^ ^        ^^^^^^^^                     \\                //^^ ^^^^^ ^^^^^^^^");
Console.WriteLine("^^^^^^^^^^^^               ^^^^ ^^^^    ^^      ^^^      ^^^  ^^^^^^^^^^^^^^^ ^^^^^ ");
Console.WriteLine("^^^^^^^^           ^^^        ^^^^^^^            ^^^^^^^^^^^^^                   ^^^^^^^ ");
await Task.Delay(500);
Console.Clear();
Console.WriteLine("             |>  ");
Console.WriteLine("        |    |    |");
Console.WriteLine("       )_)  )_)  )_)                               |>");
Console.WriteLine("      )___))___))___)\\                       |    |    |");
Console.WriteLine("     )____)____)_____)\\                     (_(  (_(  (_(");
Console.WriteLine("    ____|____|____|____\\____              /(___((___((___( ");
Console.WriteLine("----\\              //                    /(____(____(_____(");
Console.WriteLine("^^^^^^        ^^^^^^  ^^^^ ^^       _____//___|____|____|_____ ");
Console.WriteLine("^^^^^^^ ^        ^^^^^^^^                 \\                //^^ ^^^^^ ^^  ^^^^");
Console.WriteLine("^^^^^^                 ^^^^ ^^^^          ^^      ^^^    ^^^^ ^^^^^ ");
Console.WriteLine("^^^^^^^^           ^^^                   ^^^^^^^^^^^^^^^^^^^^^^^                   ^^^^^^^ ");
await Task.Delay(500);
Console.Clear();
Console.WriteLine("             |>  ");
Console.WriteLine("        |    |    |");
Console.WriteLine("       )_)  )_)  )_)                              |>");
Console.WriteLine("      )___))___))___)\\                      |    |    |");
Console.WriteLine("     )____)____)_____)\\                    (_(  (_(  (_(");
Console.WriteLine("    ____|____|____|____\\____        o o o/(___((___((___( ");
Console.WriteLine("----\\              //                   /(____(____(_____(");
Console.WriteLine("^^^^^^        ^^^^^^  ^^^^ ^^      _____//___|____|____|_____ ");
Console.WriteLine("^^^  ^^ ^        ^^^^^^^^                 \\                //^^ ^^^^^ ^^  ^^^^");
Console.WriteLine("^^^^^^                 ^^^^ ^^^^          ^^      ^^^    ^^^^ ^^^^^ ");
Console.WriteLine("^^^  ^^^           ^^^                   ^^^^^^^^^   ^^^^^  ^^^^                   ^^^^^^^ ");
await Task.Delay(500);
Console.Clear();
Console.WriteLine("             |>  ");
Console.WriteLine("        |    |    |");
Console.WriteLine("       )_)  )_)  )_)                              |>");
Console.WriteLine("      )___))___))___)\\                      |    |    |");
Console.WriteLine("     )____)____)_____)\\            o o o   (_(  (_(  (_(");
Console.WriteLine("    ____|____|____|____\\____             /(___((___((___( ");
Console.WriteLine("----\\              //                   /(____(____(_____(");
Console.WriteLine("^^^^^^        ^^^^^^  ^^^^ ^^      _____//___|____|____|_____ ");
Console.WriteLine("^^^  ^^ ^        ^^^^^^^^                 \\                //^^ ^^^^^ ^^  ^^^^");
Console.WriteLine("^^^^^^                 ^^^^ ^^^^          ^^      ^^^    ^^^^ ^^^^^ ");
Console.WriteLine("^^^  ^^^           ^^^                   ^^^^^^^^^   ^^^^^  ^^^^                   ^^^^^^^ ");
await Task.Delay(500);
Console.Clear();
Console.WriteLine("             |>  ");
Console.WriteLine("        |    |    |");
Console.WriteLine("       )_)  )_)  )_)                              |>");
Console.WriteLine("      )___))___))___)\\          o o o       |    |    |");
Console.WriteLine("     )____)____)_____)\\                    (_(  (_(  (_(");
Console.WriteLine("    ____|____|____|____\\____             /(___((___((___( ");
Console.WriteLine("----\\              //                   /(____(____(_____(");
Console.WriteLine("^^^^^^        ^^^^^^  ^^^^ ^^      _____//___|____|____|_____ ");
Console.WriteLine("^^^  ^^ ^        ^^^^^^^^                 \\                //^^ ^^^^^ ^^  ^^^^");
Console.WriteLine("^^^^^^   ^^^^^^^^^^^^     ^^^^ ^^^^          ^^      ^^^    ^^^^ ^^^^^ ");
Console.WriteLine("^^^  ^^^           ^^^^^^^^^        ^^^^^^       ^^^^^^^^^   ^^^^^  ^^^^                   ^^^^^^^ ");
await Task.Delay(500);
Console.Clear();
Console.WriteLine("             |>  ");
Console.WriteLine("        |    |    |");
Console.WriteLine("       )_)  )_)  )_)                              |>");
Console.WriteLine("      )___))___))___)\\                      |    |    |");
Console.WriteLine("     )____)____)_____)\\     o o o          (_(  (_(  (_(");
Console.WriteLine("    ____|____|____|____\\____             /(___((___((___( ");
Console.WriteLine("----\\              //                   /(____(____(_____(");
Console.WriteLine("^^^^^^        ^^^^^^  ^^^^ ^^      _____//___|____|____|_____ ");
Console.WriteLine("^^^  ^^ ^        ^^^^^^^^                 \\                //^^ ^^^^^ ^^  ^^^^");
Console.WriteLine("^^^^^^   ^^^^^^^^^^^^     ^^^^ ^^^^   ^^      ^^^    ^^^^ ^^^^^ ");
Console.WriteLine("^^^  ^^^           ^^^^^^^^^        ^^^^^^ ^^^^^^^^^   ^^^^^  ^^^^                   ^^^^^^^ ");
await Task.Delay(500);
Console.Clear();
Console.WriteLine("             |>  ");
Console.WriteLine("        |    |    |");
Console.WriteLine("       )_)  )_)  )_)                              |>");
Console.WriteLine("      )___))___))___)\\                      |    |    |");
Console.WriteLine("     )____)____)_____)\\   o o              (_(  (_(  (_(");
Console.WriteLine("    ____|____|____|____\\_o__             /(___((___((___( ");
Console.WriteLine("----\\              //                   /(____(____(_____(");
Console.WriteLine("^^^^^^        ^^^^^^  ^^^^ ^^      _____//___|____|____|_____ ");
Console.WriteLine("^^^  ^^ ^        ^^^^^^^^                 \\                //^^ ^^^^^ ^^  ^^^^");
Console.WriteLine("^^^^^^   ^^^^^^^^     ^^^^ ^^^^   ^^      ^^^    ^^^^ ^^^^^ ");
Console.WriteLine("^^^  ^^^           ^^^^^^^^^        ^^^^^^ ^^^^^^   ^^^^^  ^^^^                   ^^^^^^^ ");
await Task.Delay(500);
Console.Clear();
Console.WriteLine("             |>  ");
Console.WriteLine("        |    |    |");
Console.WriteLine("       )_)  )_)  )_)                              |>");
Console.WriteLine("      )___))___))___)\\                      |    |    |");
Console.WriteLine("     )____)____)_____o\\                    (_(  (_(  (_(");
Console.WriteLine("    ____|____|____|_o__\\___               /(___((___((___( ");
Console.WriteLine("----\\              //                   /(____(____(_____(");
Console.WriteLine("^^^^^^        ^^^^^^  ^^^^ ^^      _____//___|____|____|_____ ");
Console.WriteLine("^^^  ^^ ^        ^^^ ^^^^^                 \\                //^^ ^^^^  ^ ^^  ^^^^");
Console.WriteLine("^^^^^^   ^^^^  ^^^^     ^^^^ ^^^^   ^^      ^^^    ^^^^ ^^^^^ ");
Console.WriteLine("^^^  ^^^           ^^^^^^^^^        ^^^^^^ ^^^^   ^^   ^^^^^  ^^^^                   ^^^^^^^ ");
await Task.Delay(500);
Console.Clear();
Console.WriteLine("             |>  ");
Console.WriteLine("        |    |    |");
Console.WriteLine("       )_)  )_)  )_)                              |>");
Console.WriteLine("      )___))___))___)\\                      |    |    |");
Console.WriteLine("     )____)____)_____)\\                    (_(  (_(  (_(");
Console.WriteLine("    ____|____|____|_o__\\___              /(___((___((___( ");
Console.WriteLine("----\\              //                   /(____(____(_____(");
Console.WriteLine("^^^^^^        ^^^^^^  ^^^^ ^^      _____//___|____|____|_____ ");
Console.WriteLine("^^^  ^^ ^        ^^^ ^^^^^                 \\                //^^ ^^^^  ^ ^^  ^^^^");
Console.WriteLine("^^^^^^   ^^^^  ^^^^     ^^^^ ^^^^   ^^      ^^^    ^^^^ ^^^^^ ");
Console.WriteLine("^^^  ^^^           ^^^^^^      ^^^        ^^^^    ^^ ^^^^   ^^   ^^^^^  ^^^^                   ^^^^^^^ ");
await Task.Delay(500);
Console.Clear();
Console.WriteLine("             |>  ");
Console.WriteLine("        |    |    |");
Console.WriteLine("       )_)  )_)  )_)                              |>");
Console.WriteLine("      )___))___))___)\\                      |    |    |");
Console.WriteLine("     )____)____)_____)\\                    (_(  (_(  (_(");
Console.WriteLine("    ____|____|____|____\\___              /(___((___((___( ");
Console.WriteLine("----\\              //                   /(____(____(_____(");
Console.WriteLine("^^^^^^        ^^^^^^  ^^^^ ^^      _____//___|____|____|_____ ");
Console.WriteLine("^^^  ^^ ^        ^^^ ^^^^^                 \\                //^^ ^^^^  ^ ^^  ^^^^");
Console.WriteLine("^^^^^^   ^^^^  ^^^^     ^^^^ ^^^^   ^^      ^^^    ^^^^ ^^^^^ ");
Console.WriteLine("^^^  ^^^           ^^^^^^      ^^^        ^^^^    ^^ ^^^^   ^^   ^^^^^  ^^^^                   ^^^^^^^ ");
await Task.Delay(500);
Console.Clear();
}}
