class Animations
{
public async void animation()
{
Console.WriteLine("             |> \ ");
Console.WriteLine("        |    |    |");
Console.WriteLine("       )_)  )_)  )_)                                       |>");
Console.WriteLine("      )___))___))___)\                                |    |    |");
Console.WriteLine("     )____)____)_____)\                              (_(  (_(  (_(");
Console.WriteLine("    ____|____|____|___\\_____                      /(___((___((___( ");
Console.WriteLine("----\\              //                            /(____(____(_____(");
Console.WriteLine("^^^^^^^^^^^^^^^^^^^^  ^^^^ ^^^^^^^^^^       _____//___|____|____|_____ ");
Console.WriteLine("^^^^^^^ ^        ^^^^^^^^                          \\                //^^ ^^^^^ ^^^^^^^^");
Console.WriteLine("^^^^^^^^^^^^               ^^^^ ^^^^    ^^      ^^^      ^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^ ");
Console.WriteLine("^^^^^^^^            ^^^^^^^^^^^^                          ^^^^^^^^^^^^^            ^^^^^^^^^^^^^ ");
await Task.Delay(1000);
Console.Clear();
Console.WriteLine("             |>  ");
Console.WriteLine("        |    |    |");
Console.WriteLine("       )_)  )_)  )_)                                    |>");
Console.WriteLine("      )___))___))___)\                             |    |    |");
Console.WriteLine("     )____)____)_____)\                           (_(  (_(  (_(");
Console.WriteLine("    ____|____|____|___\\_____                   /(___((___((___( ");
Console.WriteLine("----\\              //                         /(____(____(_____(");
Console.WriteLine("^^^^^^   ^^^^^^^^^^^  ^^^^ ^^^  ^^^^^    _____//___|____|____|_____ ");
Console.WriteLine("^^^^^^^ ^        ^^^^^^^^                       \\                //^^ ^^^^^ ^   ^^^^^");
Console.WriteLine("^^^^^^^  ^^^^^           ^^^  ^ ^^^^    ^^      ^^^      ^^^  ^^^^^^^^^^^^^   ^^^^^^^^^^^^ ^^^^^ ");
Console.WriteLine("^^^^^^^^            ^^^^^^^^^^^^                          ^^^^^^^^^            ^^^^^^^   ^^^^^^ ");
await Task.Delay(1000);
Console.Clear();
Console.WriteLine("             |>  ");
Console.WriteLine("        |    |    |");
Console.WriteLine("       )_)  )_)  )_)                                  |>");
Console.WriteLine("      )___))___))___)\                           |    |    |");
Console.WriteLine("     )____)____)_____)\                         (_(  (_(  (_(");
Console.WriteLine("    ____|____|____|___\\____                  /(___((___((___( ");
Console.WriteLine("----\\              //                       /(____(____(_____(");
Console.WriteLine("^^^^^^        ^^^^^^  ^^^^ ^^   ^^     _____//___|____|____|_____ ");
Console.WriteLine("^^^^^^^ ^        ^^^^^^^^                     \\                //^^ ^^^^^ ^^^^^^^^");
Console.WriteLine("^^^^^^^^^^^^               ^^^^ ^^^^    ^^      ^^^      ^^^  ^^^^^^^^^^^^^^^ ^^^^^ ");
Console.WriteLine("^^^^^^^^           ^^^        ^^^^^^^            ^^^^^^^^^^^^^                   ^^^^^^^ ");
await Task.Delay(1000);
Console.Clear();
Console.WriteLine("             |>  ");
Console.WriteLine("        |    |    |");
Console.WriteLine("       )_)  )_)  )_)                              |>");
Console.WriteLine("      )___))___))___)\                       |    |    |");
Console.WriteLine("     )____)____)_____)\                     (_(  (_(  (_(");
Console.WriteLine("    ____|____|____|___\\____              /(___((___((___( ");
Console.WriteLine("----\\              //                   /(____(____(_____(");
Console.WriteLine("^^^^^^        ^^^^^^  ^^^^ ^^      _____//___|____|____|_____ ");
Console.WriteLine("^^^^^^^ ^        ^^^^^^^^                 \\                //^^ ^^^^^ ^^  ^^^^");
Console.WriteLine("^^^^^^                 ^^^^ ^^^^          ^^      ^^^    ^^^^ ^^^^^ ");
Console.WriteLine("^^^^^^^^           ^^^                   ^^^^^^^^^^^^^^^^^^^^^^^                   ^^^^^^^ ");
await Task.Delay(1000);
Console.Clear();
Console.WriteLine("             |>  ");
Console.WriteLine("        |    |    |");
Console.WriteLine("       )_)  )_)  )_)                              |>");
Console.WriteLine("      )___))___))___)\                       |    |    |");
Console.WriteLine("     )____)____)_____)\                     (_(  (_(  (_(");
Console.WriteLine("    ____|____|____|___\\____        o o o /(___((___((___( ");
Console.WriteLine("----\\              //                   /(____(____(_____(");
Console.WriteLine("^^^^^^        ^^^^^^  ^^^^ ^^      _____//___|____|____|_____ ");
Console.WriteLine("^^^  ^^ ^        ^^^^^^^^                 \\                //^^ ^^^^^ ^^  ^^^^");
Console.WriteLine("^^^^^^                 ^^^^ ^^^^          ^^      ^^^    ^^^^ ^^^^^ ");
Console.WriteLine("^^^  ^^^           ^^^                   ^^^^^^^^^   ^^^^^  ^^^^                   ^^^^^^^ ");
await Task.Delay(1000);
Console.Clear();
Console.WriteLine("             |>  ");
Console.WriteLine("        |    |    |");
Console.WriteLine("       )_)  )_)  )_)                              |>");
Console.WriteLine("      )___))___))___)\                       |    |    |");
Console.WriteLine("     )____)____)_____)\            o o o    (_(  (_(  (_(");
Console.WriteLine("    ____|____|____|___\\____              /(___((___((___( ");
Console.WriteLine("----\\              //                   /(____(____(_____(");
Console.WriteLine("^^^^^^        ^^^^^^  ^^^^ ^^      _____//___|____|____|_____ ");
Console.WriteLine("^^^  ^^ ^        ^^^^^^^^                 \\                //^^ ^^^^^ ^^  ^^^^");
Console.WriteLine("^^^^^^                 ^^^^ ^^^^          ^^      ^^^    ^^^^ ^^^^^ ");
Console.WriteLine("^^^  ^^^           ^^^                   ^^^^^^^^^   ^^^^^  ^^^^                   ^^^^^^^ ");
await Task.Delay(1000);
Console.Clear();
Console.WriteLine("             |>  ");
Console.WriteLine("        |    |    |");
Console.WriteLine("       )_)  )_)  )_)                              |>");
Console.WriteLine("      )___))___))___)\          o o o        |    |    |");
Console.WriteLine("     )____)____)_____)\                     (_(  (_(  (_(");
Console.WriteLine("    ____|____|____|___\\____              /(___((___((___( ");
Console.WriteLine("----\\              //                   /(____(____(_____(");
Console.WriteLine("^^^^^^        ^^^^^^  ^^^^ ^^      _____//___|____|____|_____ ");
Console.WriteLine("^^^  ^^ ^        ^^^^^^^^                 \\                //^^ ^^^^^ ^^  ^^^^");
Console.WriteLine("^^^^^^   ^^^^^^^^^^^^     ^^^^ ^^^^          ^^      ^^^    ^^^^ ^^^^^ ");
Console.WriteLine("^^^  ^^^           ^^^^^^^^^        ^^^^^^       ^^^^^^^^^   ^^^^^  ^^^^                   ^^^^^^^ ");
await Task.Delay(1000);
Console.Clear();
Console.WriteLine("             |>  ");
Console.WriteLine("        |    |    |");
Console.WriteLine("       )_)  )_)  )_)                              |>");
Console.WriteLine("      )___))___))___)\                       |    |    |");
Console.WriteLine("     )____)____)_____)\     o o o           (_(  (_(  (_(");
Console.WriteLine("    ____|____|____|___\\____              /(___((___((___( ");
Console.WriteLine("----\\              //                   /(____(____(_____(");
Console.WriteLine("^^^^^^        ^^^^^^  ^^^^ ^^      _____//___|____|____|_____ ");
Console.WriteLine("^^^  ^^ ^        ^^^^^^^^                 \\                //^^ ^^^^^ ^^  ^^^^");
Console.WriteLine("^^^^^^   ^^^^^^^^^^^^     ^^^^ ^^^^   ^^      ^^^    ^^^^ ^^^^^ ");
Console.WriteLine("^^^  ^^^           ^^^^^^^^^        ^^^^^^ ^^^^^^^^^   ^^^^^  ^^^^                   ^^^^^^^ ");
await Task.Delay(1000);
Console.Clear();
Console.WriteLine("             |>  ");
Console.WriteLine("        |    |    |");
Console.WriteLine("       )_)  )_)  )_)                              |>");
Console.WriteLine("      )___))___))___)\                       |    |    |");
Console.WriteLine("     )____)____)_____)\    o o              (_(  (_(  (_(");
Console.WriteLine("    ____|____|____|___\\_o__              /(___((___((___( ");
Console.WriteLine("----\\              //                   /(____(____(_____(");
Console.WriteLine("^^^^^^        ^^^^^^  ^^^^ ^^      _____//___|____|____|_____ ");
Console.WriteLine("^^^  ^^ ^        ^^^^^^^^                 \\                //^^ ^^^^^ ^^  ^^^^");
Console.WriteLine("^^^^^^   ^^^^^^^^     ^^^^ ^^^^   ^^      ^^^    ^^^^ ^^^^^ ");
Console.WriteLine("^^^  ^^^           ^^^^^^^^^        ^^^^^^ ^^^^^^   ^^^^^  ^^^^                   ^^^^^^^ ");
await Task.Delay(1000);
Console.Clear();
Console.WriteLine("             |>  ");
Console.WriteLine("        |    |    |");
Console.WriteLine("       )_)  )_)  )_)                              |>");
Console.WriteLine("      )___))___))___)\                       |    |    |");
Console.WriteLine("     )____)____)_____o\                     (_(  (_(  (_(");
Console.WriteLine("    ____|____|____|_o_\\___               /(___((___((___( ");
Console.WriteLine("----\\              //                   /(____(____(_____(");
Console.WriteLine("^^^^^^        ^^^^^^  ^^^^ ^^      _____//___|____|____|_____ ");
Console.WriteLine("^^^  ^^ ^        ^^^ ^^^^^                 \\                //^^ ^^^^  ^ ^^  ^^^^");
Console.WriteLine("^^^^^^   ^^^^  ^^^^     ^^^^ ^^^^   ^^      ^^^    ^^^^ ^^^^^ ");
Console.WriteLine("^^^  ^^^           ^^^^^^^^^        ^^^^^^ ^^^^   ^^   ^^^^^  ^^^^                   ^^^^^^^ ");
await Task.Delay(1000);
Console.Clear();
Console.WriteLine("             |>  ");
Console.WriteLine("        |    |    |");
Console.WriteLine("       )_)  )_)  )_)                              |>");
Console.WriteLine("      )___))___))___)\                       |    |    |");
Console.WriteLine("     )____)____)_____)\                     (_(  (_(  (_(");
Console.WriteLine("    ____|____|____|_o_\\___               /(___((___((___( ");
Console.WriteLine("----\\              //                   /(____(____(_____(");
Console.WriteLine("^^^^^^        ^^^^^^  ^^^^ ^^      _____//___|____|____|_____ ");
Console.WriteLine("^^^  ^^ ^        ^^^ ^^^^^                 \\                //^^ ^^^^  ^ ^^  ^^^^");
Console.WriteLine("^^^^^^   ^^^^  ^^^^     ^^^^ ^^^^   ^^      ^^^    ^^^^ ^^^^^ ");
Console.WriteLine("^^^  ^^^           ^^^^^^      ^^^        ^^^^    ^^ ^^^^   ^^   ^^^^^  ^^^^                   ^^^^^^^ ");
await Task.Delay(1000);
Console.Clear();
Console.WriteLine("             |>  ");
Console.WriteLine("        |    |    |");
Console.WriteLine("       )_)  )_)  )_)                              |>");
Console.WriteLine("      )___))___))___)\                       |    |    |");
Console.WriteLine("     )____)____)_____)\                     (_(  (_(  (_(");
Console.WriteLine("    ____|____|____|___\\___               /(___((___((___( ");
Console.WriteLine("----\\              //                   /(____(____(_____(");
Console.WriteLine("^^^^^^        ^^^^^^  ^^^^ ^^      _____//___|____|____|_____ ");
Console.WriteLine("^^^  ^^ ^        ^^^ ^^^^^                 \\                //^^ ^^^^  ^ ^^  ^^^^");
Console.WriteLine("^^^^^^   ^^^^  ^^^^     ^^^^ ^^^^   ^^      ^^^    ^^^^ ^^^^^ ");
Console.WriteLine("^^^  ^^^           ^^^^^^      ^^^        ^^^^    ^^ ^^^^   ^^   ^^^^^  ^^^^                   ^^^^^^^ ");
await Task.Delay(1000);
Console.Clear();
Console.WriteLine($"Enemy ship health: {enemyShip.Health}/{enemyShip.MaxHealth}\nYour current health: {playerShip.Health}/{playerShip.MaxHealth}")
    }
}